services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: northwind
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres -d northwind"]
      interval: 5s
      timeout: 3s
      retries: 20

  adminer:
    image: adminer
    depends_on: [db]
    ports: ["8080:8080"]
  app:
    build: .
    depends_on:
      - db
    env_file: .env
    ports: ["8000:8000"]
    # Optional live-editing during dev:
    volumes:
      - .:/app


volumes:
  pgdata:

